import Footer from "@/components/shared/footer";
import Header from "@/components/shared/header";
import { Metadata } from "next";
import React from "react";

// Define a type for the props
type RootLayoutProps = {
  children: React.ReactNode;
  modal?: React.ReactNode; // Make modal optional if it's not always present
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <div className="flex h-screen flex-col">
      <Header />
      <main className="flex-1 wrapper">{children}</main>
      <Footer />
    </div>
  );
}
