name: Feature Request
description: Suggest an idea for this project.
title: "[FEAT]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to suggest a New Feature!
  - type: textarea
    id: new-feature
    attributes:
      label: What is the Feature/Idea?
      description: "A new feature!"
      value: |
        ## Is your feature request related to a problem/idea? Please describe.
        A clear and concise description of what the problem/idea is.

        ## Describe the solution you'd like
        A clear and concise description of what you want to happen.

        ## Describe alternatives you've considered
        A clear and concise description of any alternative solutions or features you've considered.

        ## Additional context
        Add any other context or screenshots about the feature request here.
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/shreyvarshney1/digitalreads/blob/master/CODE_OF_CONDUCT.md).
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true